### ISSUE TITLE
View Chapter members

### ISSUE THREAD

**Issue by audgster** [UltimateSoftware/fg-mobile#14]
When viewing chapter information, I want to be able to expand the list of members to see all members

- Create a new view to show members in a grid
- Create service to fetch member list from backend asynchronously

**Comment by markd315** [comment]
Right now, this will show all members for a given chapter:

```
curl -X GET \
  http://localhost:5000/chapters 
```

The issue is that profiles are not well coupled to chapters, and that we might have a broken route for adding them.

```
curl -X POST \
  http://localhost:5000/chapters/9d730767-98a7-4a79-b239-48e151c33889/members/56e54f83-7c23-464a-be63-84e6b895dd44 \
  -H 'Content-Type: application/json' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F firstName=tester \
  -F lastName=del \
  -F id=56e54f83-7c23-464a-be63-84e6b895dd44
```

This sample cURL from our postman collection doesn't seem to affect that list, and is also not a RESTful route.

Make a ticket for whatever else you need at https://github.com/UltimateSoftware/fg-profile/issues

**Comment by Ajvigueras** [comment]
#28

**Comment by audgster** [comment]
Closing for new issues
